composio/cli/add.py
composio/client/__init__.py

Bug fix
___
- Added `auth_mode` parameter to connection initiation in `add.py`.
- Fixed app details retrieval and updated integration creation to use `app.appId` in `__init__.py`.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix
<tr>
<td>
<details>
<summary><strong>add.py</strong><dd><code>Add `auth_mode` parameter to connection initiation.</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
composio/cli/add.py
- Added `auth_mode` parameter when initiating a connection.
</details>
</td>
<td><a href="https://github.com/SamparkAI/composio/pull/62/files#diff-7cd5ff3775517d5c193b445990cb43a4fd785eaa3ce17f23dfe48bba9d7b5b6f">+1/-0</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    
<tr> …

Fix slack default connector issue

---

plugins/autogen/composio_autogen/toolset.py
plugins/claude/composio_claude/toolset.py
plugins/griptape/composio_griptape/toolset.py
plugins/julep/composio_julep/toolset.py
plugins/langchain/composio_langchain/toolset.py
plugins/lyzr/composio_lyzr/toolset.py
plugins/openai/composio_openai/toolset.py

Enhancement
___
- Added an optional `entity_id` parameter to various methods across multiple toolsets.
- Updated docstrings to reflect the inclusion of the `entity_id` parameter.
- Modified method calls to utilize the `entity_id` parameter if provided, defaulting to `self.entity_id` otherwise.
___
<tr>
<td>
<details>
<summary><strong>toolset.py</strong><dd><code>Add `entity_id` parameter to toolset methods</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
plugins/autogen/composio_autogen/toolset.py
<li>Added <code>entity_id</code> parameter to multiple methods.<br> <li> Updated …

Entity id argument usage on plugins

---

plugins/autogen/setup.py
plugins/claude/setup.py
plugins/crew_ai/setup.py
plugins/griptape/setup.py
plugins/julep/setup.py
plugins/langchain/setup.py
plugins/lyzr/setup.py
plugins/openai/setup.py
setup.py

Enhancement
___
- Bumped version to `0.3.9-rc.2` across multiple plugins and core package.
- Updated `composio_core` dependency to `0.3.9-rc.2` in relevant plugins.
___
</strong></td><td><details><summary>9 files</summary><table>
<tr>
<td>
<details>
<summary><strong>setup.py</strong><dd><code>Bump version and update dependency in Autogen plugin</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
plugins/autogen/setup.py
<li>Bumped version to <code>0.3.9-rc.2</code><br> <li> Updated <code>composio_core</code> dependency to <code>0.3.9-rc.2</code><br>
</details>
</td>
<td><a href="https://github.com/ComposioHQ/composio/pull/114/files#diff-8419a1c729ec9b7568e9db55762c9b42aa …

feat: bump to 0.3.9-rc.2

---

composio/cli/__init__.py
composio/cli/utils/__init__.py

enhancement
___
- Added `HelpfulCmdBase` import in `composio/cli/__init__.py` to enhance CLI functionality.
- Introduced `HelpfulCmdBase` in `composio/cli/utils/__init__.py` for better modularization.
___
<tr>
<td>
<details>
<summary><strong>__init__.py</strong><dd><code>Import `HelpfulCmdBase` in CLI initialization.</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
composio/cli/__init__.py
- Imported `HelpfulCmdBase` from `composio.cli.utils`.
</details>
</td>
<td><a href="https://github.com/ComposioHQ/composio/pull/116/files#diff-8673a267670e10eac352c3a1cf5fcdbb1dd3c8f1ed12ebb9b5126b1836d45e36">+1/-0 …

fix: add init in utils

---

python/composio/client/collections.py
python/composio/tools/__init__.py

Enhancement, Bug fix
___
- Generalized the `ActionParametersModel` and `ActionResponseModel` by changing the `properties` field to accept any type (`t.Any`).
- Removed the `ActionParameterPropertyModel` and `ActionResponsePropertyModel` classes as they are no longer needed.
- Updated the `execute` method to correctly handle the `file_readable` property when `properties` is a dictionary.
- Suppressed error messages in the `execute_action` method by replacing the print statement with `pass`.
___
<tr>
<td>
<details>
<summary><strong>collections.py</strong><dd><code>Generalize action parameter and response models</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …

Make req and resp any

---

docs/apps/twitter.mdx

minor fix
___
Documentation
___
- Fixed a minor typographical error in the Twitter integration documentation by removing a duplicated word.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation
<tr>
<td>
<details>
<summary><strong>twitter.mdx</strong><dd><code>Fix minor typographical error in Twitter integration doc</code>&nbsp; </dd></summary>
<hr>
docs/apps/twitter.mdx
- Fixed a minor typographical error by removing a duplicated word.
</details>
</td>
<td><a href="https://github.com/ComposioHQ/composio/pull/210/files#diff-dde3e749bbcdc04973e8b135e6321dd7748ce32e47e3eb8683c3d94511cef949">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    
</table></td></tr></tr></tbody></table>
___
> 💡 …

docs: update twitter.mdx

---

js/src/sdk/client/services.gen.ts
js/src/sdk/client/types.gen.ts
js/src/sdk/index.ts

Bug fix, Enhancement
___
- Added `appNames` query parameter to the `listAllConnections` function in `services.gen.ts`.
- Added `appNames` and `status` fields to `ListAllConnectionsData` type in `types.gen.ts`.
- Updated `Entity.execute` method to include `appNames` and `status` filters when listing connected accounts in `index.ts`.
___
<tr>
<td>
<details>
<summary><strong>services.gen.ts</strong><dd><code>Add `appNames` query parameter to listAllConnections function</code></dd></summary>
<hr>
js/src/sdk/client/services.gen.ts
<li>Added <code>appNames</code> query parameter to the <code>listAllConnections</code> function.<br>
</details>
</td>
<td><a …

fix: auto get connected accounts in entity.execute()

---

README-CN.md
README-JP.md
README.md

I created Japanese translated README.
___
Documentation
___
- Added a new Japanese README file (`README-JP.md`) with comprehensive documentation including introduction, features, getting started guides for Python and JavaScript, examples, and contribution guidelines.
- Updated the language selection section in `README.md` and `README-CN.md` to include a link to the new Japanese README.
___
<tr>
<td>
<details>
<summary><strong>README-CN.md</strong><dd><code>Add link to Japanese README in language selection</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
README-CN.md
<li>Added link to Japanese README …

docs: add Japanese README

---

python/composio/client/collections.py

Enhancement
___
- Added a new method `get_by_id` in `python/composio/client/collections.py` to retrieve an integration by its ID.
- Included a docstring to describe the new method's parameters and return type.
- Utilized the existing `_raise_if_required` method to handle HTTP response errors.
___
<tr>
<td>
<details>
<summary><strong>collections.py</strong><dd><code>Add method to retrieve integration by ID</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
python/composio/client/collections.py
<li>Added a new method <code>get_by_id</code> to retrieve an …

Add integration by id function

---

python/composio/tools/toolset.py
python/plugins/openai/openai_demo.py

Example Usage:
```
composio_toolset.get_agent_instructions(
apps=[App.GMAIL],
actions=[
Action.GITHUB_ACTIONS_ADD_CUSTOM_LABELS_TO_SELF_HOSTED_RUNNER_FOR_ORG,
Action.ASANA_ALLOCATIONS_DELETE_ALLOCATION_BY_ID
]
)
```
> You have various tools, among which for interacting with **gmail** you might use gmail_send_email, gmail_create_email_draft, gmail_add_label_to_email, gmail_list_labels, gmail_reply_to_thread, gmail_fetch_emails_with_label, gmail_fetch_last_three_messages, gmail_fetch_message_by_thread_id and gmail_find_email_id tools, for interacting with **asana** you might use asana_allocations_delete_allocation_by_id tools, for interacting with **github** you might use github_actions_add_custom_labels_to_self_hosted_runner_for_org tools. Whichever tool is useful to execute your task, use …

feat: get_agent_instruction method added to toolset

---

python/composio/client/collections.py

Enhancement
___
- Changed the return type of `_handle_callback` method from `None` to `t.Any`.
- Modified the `_handle_callback` method to return the result of the `callback` function.
___
<tr>
<td>
<details>
<summary><strong>collections.py</strong><dd><code>Modify `_handle_callback` to return callback result</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
python/composio/client/collections.py
<li>Changed the return type of <code>_handle_callback</code> method from <code>None</code> to <code>t.Any</code>.<br> <li> Modified the method to return the result of the <code>callback</code> function.<br>
</details>
</td>
<td><a …

feat: return value from _handle_callback for playground

---

python/composio/utils/shared.py

Bug fix
___
- Added handling for `anyOf` in parameter schema to ensure proper type extraction.
- Fixed the default value assignment logic to handle cases where `param_type` is `None`.
- Included a debug print statement to output `param_schema` for better debugging.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>shared.py</strong><dd><code>Fix and enhance optional parameter handling in schema</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
python/composio/utils/shared.py
<li>Added handling for <code>anyOf</code> in parameter schema.<br> <li> Fixed default value assignment when <code>param_type</code> is <code>None</code>.<br> <li> Included debug print …

Fix optional handling

---

python/composio/tools/toolset.py

enhancement
___
- Removed the print statement for error checking in the `_execute_remote` method of `toolset.py`.
- Replaced the print statement with `pass` to handle exceptions silently.
___
<tr>
<td>
<details>
<summary><strong>toolset.py</strong><dd><code>Remove error checking print statement in `_execute_remote` method</code></dd></summary>
<hr>
python/composio/tools/toolset.py
<li>Removed print statement for error checking in <code>_execute_remote</code> method.<br> <li> Replaced print statement with <code>pass</code> to handle exceptions silently.<br>
</details>
</td>
<td><a href="https://github.com/ComposioHQ/composio/pull/323/files#diff-89b5c0aec15f …

chore: remove Error checking file response print statement

---

python/composio/tools/toolset.py

Bug fix
___
- Fixed an issue in `_serialize_execute_params` method where `None` values were not being excluded during JSON serialization.
- Updated `model_dump_json` and `dict` method calls to include `exclude_none=True` parameter.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>toolset.py</strong><dd><code>Exclude `None` values in JSON serialization for models</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
python/composio/tools/toolset.py
<li>Updated <code>_serialize_execute_params</code> method to exclude <code>None</code> values in <br>JSON serialization.<br> <li> Modified <code>model_dump_json</code> and <code>dict</code> methods to use …

added exclude none in serialiser

---

python/composio/cli/add.py

Enhancement
___
- Enhanced the `add_integration` function to accept and pass `scopes` parameter.
- Modified `_handle_oauth` function to handle `scopes` and pass it to `_get_auth_config`.
- Ensured OAuth scopes are properly integrated into the connection initiation process.
___
<tr>
<td>
<details>
<summary><strong>add.py</strong><dd><code>Add support for OAuth scopes in integration functions</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
python/composio/cli/add.py
<li>Added <code>scopes</code> parameter to <code>add_integration</code> and <code>_handle_oauth</code> functions.<br> <li> Updated <code>_handle_oauth</code> to pass <code>scopes</code> …

Pass scope for oauth

---

docs/guides/javascript/interpreter-agent.mdx
docs/guides/python/rag_agent.mdx
docs/guides/python/research-assistant.mdx
docs/javascript/langchain.mdx
js/examples/langchain/demo.mjs
js/examples/langchain/demo.ts
js/examples/langchain/sample.mjs
python/examples/image_search/image_search_crewai/main.py
python/examples/image_search/image_search_langchain/image_search_frontend.py
python/examples/image_search/image_search_langchain/main.py
python/examples/image_search/image_search_langgraph/main.py
python/examples/image_search/image_search_llamaindex/main.py
python/examples/local_tools/autogen_math.py
python/examples/miscellaneous/gmail_send_attachment_crew.py
python/examples/pr_agent/pr_agent_crewai/main.py
python/examples/pr_agent/pr_agent_langchain/main.py
python/examples/pr_agent/pr_agent_llama_index/main.py
python/plugins/autogen/README.md
python/plugins/autogen/autogen_demo.py
python/plugins/julep/README.md
python/plugins/julep/julep_demo.py
python/plugins/langchain/langchain_demo.py
python/swe/examples/crewai_agent/agent.py

Documentation, Enhancement
___
- Removed manual API key input and setting across multiple files.
- Changed model initialization to `gpt-4o` across multiple files.
- Introduced `Crew` for task execution in relevant files.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>17 files</summary><table>
<tr>
<td>
<details>
<summary><strong>main.py</strong><dd><code>Update model initialization and task execution</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
python/examples/image_search/image_search_crewai/main.py
<li>Removed manual API key input and setting.<br> <li> Changed model initialization to <code>gpt-4o</code>.<br> <li> Introduced …

fix docs - env variables, default model and init code

---

docs/mint.json
docs/swekit/benchmarks.mdx
docs/swekit/introduction.mdx
docs/swekit/workspace-env.mdx

Documentation
___
- Added new documentation for SweKit, including introduction, benchmarks, and workspace environments.
- Updated `mint.json` to include the new SweKit documentation structure.
___
<tr>
<td>
<details>
<summary><strong>mint.json</strong><dd><code>Add SweKit group and pages to documentation structure</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
docs/mint.json
<li>Added a new group <code>SweKit</code> with pages for introduction, workspace <br>environments, and benchmarks.<br> <li> Removed unnecessary blank lines.<br>
</details>
</td>
<td><a href="https://github.com/ComposioHQ/composio/pull/362/files#diff-c91a604899dfef4b2494c317f4 …

Added SWE Docs

---

python/Makefile

Was facing this error while running ``` make env``` in wsl
 
```
if [[ -z "$$VIRTUAL_ENV" ]]; then \
echo "No virtual environment is active"; \
```
The original code used the [[ ... ]] syntax for checking if the VIRTUAL_ENV variable was empty, but [[ ... ]] is a Bash-specific feature and wasn't being interpreted correctly in the Makefile's default shell (/bin/sh).
Replaced [[ ... ]] with [ ... ] to ensure compatibility with /bin/sh.
The -z flag is used to check if the VIRTUAL_ENV variable is either empty or undefined (i.e., a zero-length or null string).

fix: Makefile bin/sh compatibility (wsl)

---

python/examples/image_search/image_search_autogen/setup.sh
python/examples/image_search/image_search_crewai/setup.sh
python/examples/image_search/image_search_langchain/setup.sh
python/examples/image_search/image_search_langgraph/setup.sh
python/examples/image_search/image_search_llamaindex/setup.sh
python/examples/sql_agent/setup.sh
python/examples/sql_agent/sql_agent_plotter_crewai/setup.sh
python/examples/sql_agent/sql_agent_plotter_langchain/setup.sh
python/examples/sql_agent/sql_agent_plotter_llama_index/setup.sh

- `sed` command is differently implemented in both mac and linux.
- mac has BSD utility while linux has GNU utility.
- New approach will work on both
Fixes issue #465

fix: use `sed -i.bak` instead of plain `sed`

---

python/composio/tools/env/filemanager/manager.py
python/composio/tools/local/filetool/actions/__init__.py
python/composio/tools/local/filetool/actions/rename.py
python/composio/tools/local/filetool/tool.py

Addresses [issue](https://github.com/ComposioHQ/composio/issues/146)

feat: add feature to rename file and directory (`filetools`)

---

.github/workflows/release_js_sdk.yml
js/package.json

- Manually update the version in package.json
- Merge to master and release new version

feat: release github action

---

python/composio/client/collections.py

fix: ignore unused parameters passed to execute_action

---

python/composio/tools/local/codeanalysis/actions/create_codemap.py
python/composio/tools/local/codeanalysis/tool.py
python/composio/tools/local/filetool/actions/git_clone.py

Enhance the code analysis tool's efficiency and streamline the codebase.
- **Enhancement**:
- Added a check for `create_index` in metadata to conditionally create an index in `create_codemap.py`.
- Removed the `tokenizers` dependency in `tool.py`.
- Eliminated the `git clean -fdx` command in `git_clone.py` to streamline the git reset process.
Improves the code analysis tool's efficiency and simplifies the codebase for better maintainability. 
</details>

fix: codeanalysis bug

---

js/src/sdk/models/actions.ts

- Address a bug in the JavaScript SDK related to the `advancedUseCaseSearch` method, improving the robustness of the search functionality.
- **Bug Fix**: 
- Enhanced the `advancedUseCaseSearch` method by adding a nullish coalescing operator to safely access the `apps` array, preventing runtime errors when `apps` is undefined.
- Improves the reliability of the search functionality in the JavaScript SDK by preventing potential runtime errors, enhancing the overall user experience. 
</details>

fix: js apps filter in enum usecase search method

---

js/package.json

This pull request focuses on a minor version update for the `composio-core` project.
- **Chore**:
- Updated the `package.json` file to increment the version from 0.4.6 to 0.4.7, indicating minor improvements.
- Ensures that the project dependencies are up-to-date.
- Contributes to improved version control.
- Facilitates smooth functioning of future developments. 
</details>

chore: bump 0.4.7

---

python/plugins/llamaindex/llamaindex_demo.py

The purpose of this update is to optimize the code and improve its readability in the Llama Index Demo module.
- **Code Optimization**
- **Style**: Removed a redundant print statement from `llamaindex_demo.py`, simplifying the code and enhancing readability.
- **Developer Experience**: 
- Enhances the code's readability and efficiency, making it easier for developers to understand and maintain the code.
- **User Experience**:
- This change has no direct impact on the end user as it doesn't affect functionality. 
</details>

chore: remove duplicate print of response in llamaindex demo

---

.github/workflows/common.yml
.github/workflows/examples.yml

- Introduce automated tests through scheduled GitHub Actions workflows.
- Improve communication of test failures by modifying Slack notification settings.
- **Automated Testing**: 
- Added a cron job in the GitHub Actions workflow to automate test execution every 12 hours in both `common.yml` and `examples.yml` files.
- **Slack Notifications**:
- Updated Slack notification settings to tag specific users when tests fail, excluding release commits, in both `common.yml` and `examples.yml` files.
- **CI/CD Pipeline Reliability**:
- Enhances the reliability and responsiveness of the CI/CD pipeline by automating test runs.
- **Improved Communication**:
- Enhances communication on failures for prompt resolution by notifying specific users. 
No …

ci: run every 12 hours, and tag me on failure

---

.github/workflows/common.yml
.github/workflows/examples.yml
.github/workflows/run_examples.yml

The primary aim of these updates is to enhance the CI/CD pipeline by integrating a feature that triggers example tests on the master branch and informs team members via Slack notifications when any test fails.
- **New Feature**
- Integrated Slack notifications to alert specific team members when example tests fail on the master branch.
- **Enhancement**
- Improved the CI/CD pipeline by ensuring trigger conditions for running example tests include pushes to the master branch.
- **Refactor**
- Updated information in Slack messages to notify different team members upon test failures.
These changes are expected to improve the overall efficiency of the development process. The integration of Slack notifications will ensure the right members are notified promptly about failed tests, enabling …

ci: run example tests on master branch

---

python/composio/tools/env/host/workspace.py

**Purpose**: Enhance resource efficiency in the `HostWorkspace` class.
**Changes**:
- **Enhancement**: Implemented lazy initialization for the SSH client using a boolean flag and a private setup method.
**Impact**: Improves system performance and resource management. 
</details>

fix: make ssh client initialisation lazier

---

python/composio/tools/base/abs.py
python/tests/test_tools/test_base/test_abs.py

When schema is generated for requests with fields like `baseId: str = Field(..., description="The ID of the base")` will have title `Baseid`. It should be more human readable like `Base Id`

fix: humanize field titles in req/res schema

---

.github/workflows/preview_docs.yml
.github/workflows/publish_docs.yml
CONTRIBUTING.md
fern/Makefile
fern/docs.yml
python/.gitignore
python/CLAUDE.md

Remove self-hosted TypeScript and Python SDK docs generation in favor of linking to documentation hosted on deepwiki.com. Update GitHub workflows and documentation configuration accordingly.

feat: Move SDK reference docs to deepwiki.com

---

js/src/sdk/index.ts

Currently the allowTracing flag has no impact on the sessionId. This PR fixes it by preventing generating sessionId if the `allowTracing` flag is explicitly set to false .

Fix: Disable sessionId if allowTracking is set to false

---

ts/packages/cli/src/services/composio-clients.ts
ts/packages/cli/src/services/user-config.ts

We don't need to read the app `Config` (`process.env.COMPOSIO_*` vars or `~/.composio/user_data.json`) for simple commands that don't use the client, like `composio version`.

feat(cli): introduce lazy config check

---

ts/packages/cli/src/generation/typescript/generate-index-source.ts
ts/packages/cli/test/__fixtures__/python-project-with-composio-core/uv.lock
ts/packages/cli/test/__fixtures__/typescript-project-with-composio-core/src/index.js
ts/packages/cli/test/src/commands/ts/ts.generate.cmd.test.ts
ts/packages/cli/test/src/generation/typescript/generate-index-source.test.ts
ts/packages/cli/test/src/generation/typescript/generate.test.ts

In practice:
```diff
- import { composio } from '@composio/core/generated';
+ import { Toolkits } from '@composio/core/generated';
- console.log(composio.GMAIL.tools.CREATE_EMAIL_DRAFT);
+ console.log(Toolkits.GMAIL.tools.CREATE_EMAIL_DRAFT);
```

chore(cli): rename barrel object created by "composio ts generate" from `composio` to `Toolkits`

---

fern/docs.yml

Move domain from v3.docs.composio.dev to docs.composio.dev

fix: update custom domain in documentation configuration

---

.changeset/pre.json
.changeset/red-pigs-cross.md
.changeset/yellow-mangos-kneel.md
pnpm-lock.yaml
ts/examples/langchain/package.json
ts/packages/core/CHANGELOG.md
ts/packages/core/package.json
ts/packages/core/src/models/Tools.ts
ts/packages/core/test/tools/tools.test.ts
ts/packages/providers/anthropic/CHANGELOG.md
ts/packages/providers/anthropic/package.json
ts/packages/providers/cloudflare/CHANGELOG.md
ts/packages/providers/cloudflare/package.json
ts/packages/providers/google/CHANGELOG.md
ts/packages/providers/google/package.json
ts/packages/providers/langchain/CHANGELOG.md
ts/packages/providers/langchain/package.json
ts/packages/providers/mastra/CHANGELOG.md
ts/packages/providers/mastra/package.json
ts/packages/providers/openai-agents/CHANGELOG.md
ts/packages/providers/openai-agents/package.json
ts/packages/providers/openai/CHANGELOG.md
ts/packages/providers/openai/package.json
ts/packages/providers/vercel/CHANGELOG.md
ts/packages/providers/vercel/package.json

- Fix proxy execute params [used to be treated as objects instead of arrays]
- Chore Bump langchain package versions

Fix: Treating params as array instead of object in Proxy Execute

---

pnpm-lock.yaml
ts/packages/cli/package.json
ts/packages/cli/src/bin.ts
ts/packages/cli/src/models/tools.ts
ts/packages/cli/src/models/trigger-types.ts
ts/packages/cli/src/models/utils/extract-actual.ts
ts/packages/cli/src/services/composio-clients.ts
ts/packages/cli/src/services/upgrade-binary.ts
ts/packages/cli/src/services/utils/pretty-error.ts

This PR:
- builds on top of https://github.com/ComposioHQ/composio/pull/1771 (merge that first!)
- improves the visualization of major CLI errors messages, reducing confusion
- when available, we display the error coming from Composio's backend, formatted in a human-friendly fashion

feat(cli): improve CLI errors

---

python/composio/core/models/_files.py

downloadable path was not working correctly due to the directory not being passed to `FileDownloadable.download()`

[FIX] feat: make the file downloadable path configurable

---

ts/packages/core/src/composio.ts
ts/packages/core/src/utils/session.ts
ts/packages/core/test/core/session.test.ts

Added standardized session headers to API requests that include provider information and SDK version.
- Created new utility functions in `session.ts` to generate and manage request headers:
- `getSessionHeaders`: Generates standard headers with provider name, runtime, and SDK version
- `getDefaultHeaders`: Merges custom headers with session headers
- Modified `Composio` class to use these utility functions when initializing the client and creating sessions
- Ensured headers include provider information (`x-source`), runtime (`x-runtime`), and SDK version (`x-sdk-version`)
- Added comprehensive tests to verify header generation and merging behavior
1. Create a Composio instance with different providers and verify the headers include the correct provider name:
```typescript
const …
```

feat: add support for sending source and runtime headers

---

ts/packages/cli/package.json
ts/packages/cli/src/generation/typescript/generate-index-source.ts
ts/packages/cli/test/src/generation/typescript/generate-index-source.test.ts
ts/packages/cli/test/src/generation/typescript/generate-toolkit-source.test.ts
ts/packages/cli/tsconfig.json
ts/packages/cli/tsconfig.options.json
ts/packages/cli/tsconfig.src.json
ts/packages/cli/tsconfig.test.json
ts/packages/core/tsconfig.build.json
ts/packages/core/tsconfig.json
ts/packages/core/tsup.config.ts

This PR:
- fixes existing type errors in tests
- adds `typecheck`, `typecheck:src`, `typecheck:test` tests
- this required introducing `composite: true` in `@composio/core`'s `tsconfig.json` file
- ...which in turn required a workaround due to a bug in `tsup`'s internals: https://github.com/egoist/tsup/issues/571#issuecomment-1760052931

fix(cli): fix type errors, add typecheck scripts

---

python/composio/core/models/base.py
python/composio/core/models/connected_accounts.py

Earlier it was giving following error:
```
https://backend.composio.dev/api/v3/s/LLrcVTS3
Traceback (most recent call last):
File "/Users/sushmithamallesh/Documents/projects/composio-docs-experiments/pyexperiment/test.py", line 19, in <module>
connected_account = composio.connected_accounts.wait_for_connection(connection_request.id)
File "/Users/sushmithamallesh/Documents/projects/composio-docs-experiments/pyexperiment/.venv/lib/python3.13/site-packages/composio/core/models/connected_accounts.py", line 363, in wait_for_connection
return ConnectionRequest.from_id(
~~~~~~~~~~~~~~~~~~~~~~~~~^
id=id, client=self._client
^^^^^^^^^^^^^^^^^^^^^^^^^^
).wait_for_connection(
^
TypeError: ConnectionRequest.from_id() missing 1 required positional argument: 'self'
```

Fix wait connection

---

.changeset/swift-tools-unite.md
pnpm-lock.yaml
ts/examples/vercel/package.json
ts/examples/vercel/src/stream.ts
ts/packages/providers/vercel/package.json
ts/packages/providers/vercel/src/index.ts
ts/packages/providers/vercel/test/vercel.test.ts

- Bumps package versions of AI SDK from v4 to v5 in vercel provider
- Uses zod schemas instead of json schemas in vercel provider
- Bumps the sdk version

Add support for vercel AI SDK v5
