composio/cli/add.py, composio/cli/triggers.py, composio/client/__init__.py
Bug fix, Enhancement
___
- Refactored authentication handling in `composio/cli/add.py` to support multiple auth schemes, including OAuth1, OAuth2, API Key, and Basic Auth.
- Introduced `_handle_basic_auth` and `_handle_oauth` helper functions to streamline authentication processes.
- Improved error handling by raising exceptions for unknown authentication modes.
- Updated `composio/client/__init__.py` to use `auth_config` instead of `auth_schemes` for better flexibility and accuracy in authentication configuration.
- Set `expected_from_customer` default to `True` in `AuthSchemeField` to align with expected behavior.
___
<tr>
<td>
<details> …
=> Fix auth scheme validation

README.md
Documentation
___
- Updated the logo display in the README for better support in dark and light modes.
- Adjusted the width of the logos to ensure consistent sizing.
- Italicized the main heading for improved emphasis.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation
<tr>
<td>
<details>
<summary><strong>README.md</strong><dd><code>Fix logo display and update README formatting</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
README.md
<li>Updated logo display for dark and light modes using anchor tags.<br> <li> Adjusted the width of the logos to 318px.<br> <li> Italicized the "Production Ready Toolset for AI Agents" heading.<br> …
=> fixed logo in dark mode

composio/client/collections.py, composio/client/enums.py
Bug fix
___
- Added a new `TypeModel` class to handle type definitions.
- Modified `TriggerPayloadPropertyModel` to make `type` attribute optional and added `anyOf` attribute.
- Modified `TriggerPayloadModel` to make `type` attribute optional and added `anyOf` attribute.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix
<tr>
<td>
<details>
<summary><strong>collections.py</strong><dd><code>Fix type handling in trigger payload models</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
composio/client/collections.py
<li>Added <code>TypeModel</code> class with <code>type</code> attribute.<br> <li> Updated …
=> Fix trigger base model type handling

composio/client/local_handler.py, composio/tools/__init__.py, plugins/autogen/composio_autogen/toolset.py, plugins/claude/composio_claude/toolset.py, plugins/griptape/composio_griptape/toolset.py, plugins/langchain/composio_langchain/toolset.py, plugins/lyzr/composio_lyzr/toolset.py, plugins/openai/composio_openai/toolset.py, tests/test_example.py
Enhancement, Bug fix
___
- Enhanced handling for local tools without requiring an API key by introducing `LocalToolHandler`.
- Added `get_action_schemas` method to fetch action schemas for both local and remote actions.
- Modified `execute_action` to handle local actions.
- Updated various toolset plugins to use the new `get_action_schemas` method instead of direct client action schema fetching.
___
<tr>
<td>
<details>
<summary><strong>__init__.py</strong><dd><code>Enhance local tool handling and schema fetching</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
composio/tools/__init__.py
<li>Added handling …
=> Handle local tools without API Key [ENG-900]

plugins/autogen/setup.py, plugins/claude/setup.py, plugins/crew_ai/setup.py, plugins/griptape/setup.py, plugins/julep/setup.py, plugins/langchain/setup.py, plugins/llamaindex/setup.py, plugins/lyzr/setup.py, plugins/openai/setup.py, setup.py
enhancement
___
- Updated version from `0.3.10` to `0.3.11` across multiple plugins and core package.
- Updated dependencies to reflect the new version `0.3.11` where applicable.
___
</strong></td><td><details><summary>10 files</summary><table>
<tr>
<td>
<details>
<summary><strong>setup.py</strong><dd><code>Update version and dependency for autogen plugin</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
plugins/autogen/setup.py
<li>Updated version from <code>0.3.10</code> to <code>0.3.11</code><br> <li> Updated <code>composio_core</code> dependency version to <code>0.3.11</code><br>
</details>
</td>
<td><a …
=> Change version

README.md
Documentation
___
- Updated the image paths for the Composio logo in the README.md file.
- Changed the paths from `./docs/imgs/` to `./python/docs/imgs/` to reflect the new directory structure.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation
<tr>
<td>
<details>
<summary><strong>README.md</strong><dd><code>Update image paths for Composio logo in README</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
README.md
<li>Updated image paths for the Composio logo.<br> <li> Changed paths from <code>./docs/imgs/</code> to <code>./python/docs/imgs/</code>.<br>
</details>
</td>
<td><a href="https://github.com/ComposioHQ/composio/pull/189/files#diff-b33563 …
=> fix: Update README.md for logo

python/composio/local_tools/local_workspace/submit_patch/actions/submit_patch.py, python/composio_swe/composio_swe/agent/README.md, python/composio_swe/composio_swe/agent/prompts.py, python/composio_swe/composio_swe/agent/swe.py, python/composio_swe/composio_swe/agent/swe_run.py
Enhancement, Documentation
___
- Corrected a typo and updated the docstring in `submit_patch.py`.
- Added new templates for agent backstory and issue description in `prompts.py`.
- Refactored `swe.py` to import templates from `prompts.py` and removed the main execution block.
- Added a new script `swe_run.py` to run the `CoderAgent` with a predefined issue configuration.
- Added a README file for `swe.py` with an overview, dependencies, and usage instructions.
___
<tr>
<td>
<details>
<summary><strong>submit_patch.py</strong><dd><code>Fix typo and update docstring in submit_patch.py</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
=> Make swe simple to edit

python/Makefile, python/composio/client/collections.py, python/composio_swe/benchmark/run_evaluation.py, python/composio_swe/composio_swe/agent/swe.py
Enhancement, Bug fix
___
- Set a default value for the `entity_id` parameter in the `execute` method of `collections.py`.
- Corrected import paths in `run_evaluation.py` to ensure proper module resolution.
- Modified the dataset split range in the `get_issues_dataset` function to load a different subset of data.
- Removed entity initialization and related methods in `swe.py`, and updated method calls to use `composio_client` directly.
- Replaced `Crew` initialization and kickoff with direct task execution in `swe.py`.
___
<tr>
<td>
<details>
<summary><strong>collections.py</strong><dd><code>Set default value for `entity_id` in `execute` …
=> Solve the patch issue

python/composio_swe/benchmark/get_scores.py, python/composio_swe/setup.py
- usage -
python get_scores.py --prediction_path_dir /home/shubhra/work/swe-eval
- it generates test-bed, and environment iside the prediction_path_dir
=> get scores

python/composio/client/enums.py, python/composio/local_tools/local_workspace/cmd_manager/actions/__init__.py, python/composio/local_tools/local_workspace/cmd_manager/actions/clone_github.py, python/composio/local_tools/local_workspace/cmd_manager/actions/get_patch.py, python/composio/local_tools/local_workspace/cmd_manager/actions/git_tree.py, python/composio/local_tools/local_workspace/cmd_manager/tool.py, python/composio/local_tools/local_workspace/submit_patch/actions/submit_patch.py, python/composio/local_tools/local_workspace/tests/test_workspace.py, python/composio_swe/benchmark/get_scores.py, python/composio_swe/benchmark/run_evaluation.py, python/composio_swe/composio_swe/agent/README.md, python/composio_swe/composio_swe/agent/base_swe_agent.py, python/composio_swe/composio_swe/agent/prompts.py, python/composio_swe/composio_swe/agent/requirements.txt, python/composio_swe/composio_swe/agent/swe.py, python/composio_swe/composio_swe/agent/swe_run.py, python/composio_swe/composio_swe/agent/utils.py, python/composio_swe/composio_swe/cli/cli.py
- Enhanced the `SubmitPatchRequest` and `SubmitPatch` class descriptions to include details about the diff format.
- Simplified `CoderAgentArgs` initialization and updated method calls across multiple files.
- Introduced `BaseSWEAgent` abstract class.
- Added `REVIEWER_BACKSTORY_TMPL` template for reviewer agent.
- Refactored `CoderAgent` to inherit from `BaseSWEAgent` and added reviewer agent to the workflow.
- Added utility functions for logger setup and LLM retrieval.
- Updated README to include additional setup steps and environment variables.
- Changed the patch generated to be static instead of agentic.
___
</strong></td><td><details><summary>8 files</summary><table>
<tr> …
=> Restructre SWE Agent

python/composio/local_tools/local_workspace/cmd_manager/actions/clone_github.py, python/composio/local_tools/local_workspace/tests/test_workspace.py, python/examples/swe/evaluation/visualize.py
Tests, Enhancement
___
- Added a command to get the remote URL of the origin before fetching and resetting in `clone_github.py`.
- Expanded the test in `test_workspace.py` to cover a comprehensive Git workflow including cloning, opening, editing, and resetting files.
- Standardized string formatting to use double quotes and improved HTML content generation in `visualize.py`.
___
<tr>
<td>
<details>
<summary><strong>clone_github.py</strong><dd><code>Add command to get remote URL before fetch and reset</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
python/composio/local_tools/local_workspace/cmd_manager/actions/clone_github.py
<li>Added a …
=> Add test for swe actions

cookbook/readme.md
Documentation
___
- Added a new `readme.md` file to the `cookbook` directory.
- The README file includes an overview of the Composio Cookbook.
- Provided detailed instructions on how to contribute to the Cookbook.
- Included a section for contributors to seek help via the Discord community.
___
<tr>
<td>
<details>
<summary><strong>readme.md</strong><dd><code>Add contribution guidelines and overview for Composio Cookbook</code></dd></summary>
<hr>
cookbook/readme.md
<li>Added an overview of the Composio Cookbook.<br> <li> Provided guidelines on how to contribute to the Cookbook.<br> <li> Included steps for forking the repository, creating a new folder, …
=> add cookbook

README-CN.md, README.md
Documentation
___
- Added a new README file in Chinese (`README-CN.md`) with comprehensive details about the project, including features, quick start guides for Python and JavaScript, examples, and contribution guidelines.
- Updated the main README (`README.md`) to include links for switching between English and Chinese versions.
___
<tr>
<td>
<details>
<summary><strong>README-CN.md</strong><dd><code>Add Chinese README with comprehensive project details</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
README-CN.md
<li>Added a new README file in Chinese.<br> <li> Included sections for features, quick start guides, examples, and <br>contribution …
=> add cn readme

docs/mint.json, docs/pnpm-lock.yaml, docs/sdk/javascript/cloudflare.mdx, docs/sdk/javascript/langchain.mdx, docs/sdk/javascript/openai.mdx
Added documentation for Cloudflare worker AI integration
=> feat: add cloudflare docs

js/package.json
enhancement
___
- Bumped the version of the JavaScript SDK from 0.1.4 to 0.1.5 in `package.json`.
___
<tr>
<td>
<details>
<summary><strong>package.json</strong><dd><code>Update SDK version to 0.1.5</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
js/package.json
- Bumped the version from 0.1.4 to 0.1.5.
</details>
</td>
<td><a href="https://github.com/ComposioHQ/composio/pull/270/files#diff-e51a40ac250c9696142466f114f754161e7e5102c0cdb5354548b757deb272f6">+1/-1</a>&nbsp; …
=> chore: bump js sdk to v0.1.5

python/swe/DEVELOPMENT.md, python/swe/README.md, python/swe/composio_swe/scaffold/templates/crewai/benchmark.template
Update to new flows
___
Documentation
___
- Updated the README to provide a comprehensive overview of the Composio-swe framework.
- Revised the dependencies and installation steps for clarity.
- Added a new "Getting started" section to guide users on scaffolding a new agent.
- Included instructions for adding new local tools and shell tools.
___
<tr>
<td>
<details>
<summary><strong>README.md</strong><dd><code>Comprehensive update to README for Composio-swe framework</code></dd></summary>
<hr>
python/swe/README.md
<li>Updated the overview to describe Composio-swe framework and its usage.<br> <li> Revised dependencies and installation steps.<br> <li> …
=> Update SWE Readme

python/examples/slack_bot_agent/slack_agent_ollama/.env.example, python/examples/slack_bot_agent/slack_agent_ollama/main.py, python/examples/slack_bot_agent/slack_agent_ollama/readme.md, python/examples/slack_bot_agent/slack_agent_ollama/requirements.txt, python/examples/slack_bot_agent/slack_agent_ollama/setup.sh
Enhancement, Documentation
___
- Added a new Slack bot agent using Ollama and Composio toolset, integrated with LangChain and OpenAI for message processing.
- Implemented a setup script to create a virtual environment, install dependencies, and configure Composio Slackbot triggers.
- Provided an example environment variables file for necessary API keys and bot ID.
- Added a comprehensive README guide for setting up, configuring, and running the Slack bot agent.
- Included a requirements file listing the necessary Python libraries.
___
<tr>
<td>
<details>
<summary><strong>main.py</strong><dd><code>Add Slack bot agent with Ollama and Composio …
=> feat:slack-agent ollama was added

python/composio/tools/env/docker/workspace.py, python/swe/swekit/scaffold/templates/crewai/main.template
Fixes 
1. https://composioworkspace.slack.com/archives/C05811N5HHP/p1720597601909449?thread_ts=1720539686.865209&cid=C05811N5HHP
2. https://composioworkspace.slack.com/archives/C05811N5HHP/p1720597496140609?thread_ts=1720539686.865209&cid=C05811N5HHP
___
Bug fix
___
- Enhanced the error message for Docker client initialization to provide more guidance.
- Improved handling of response output and error messages in the `main.template` file.
___
<tr>
<td>
<details>
<summary><strong>workspace.py</strong><dd><code>Improve Docker client initialization error message</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …
=> Fix swe errors

python/composio/tools/env/docker/scripts/commands/defaults.sh, python/swe/swekit/benchmark/run_evaluation.py, python/swe/swekit/benchmark/utils.py, python/tests/test_tools/test_local/test_workspace.py
Benchmarks changes to run on E2B/Fly.io
___
Enhancement, Tests
___
- Enhanced the file opening script with better messaging for file operations.
- Added `workspace_env` configuration to the evaluation process, allowing different environments.
- Updated benchmark utilities to support multiple workspace environments.
- Added new tests for Docker workspace and enhanced existing workspace tests with additional logging and checks.
___
<tr>
<td>
<details>
<summary><strong>defaults.sh</strong><dd><code>Enhance file opening script with better messaging</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …
=> Benchmarks changes to run on E2B/Fly.io

js/src/sdk/base.toolset.ts, js/src/sdk/index.ts, js/src/utils/shared.ts
Bug fix, Enhancement
___
- Added `getEnvVariable` function in `shared.ts` to safely access environment variables.
- Updated `base.toolset.ts` to use `getEnvVariable` instead of direct environment variable access.
- Updated `index.ts` to use `getEnvVariable` instead of direct environment variable access.
___
<tr>
<td>
<details>
<summary><strong>base.toolset.ts</strong><dd><code>Use <code>getEnvVariable</code> for environment variable access in <code>base.toolset.ts</code></code></dd></summary>
<hr>
js/src/sdk/base.toolset.ts
<li>Imported <code>getEnvVariable</code> function.<br> <li> Replaced direct environment variable access with …
=> fix: use getEnvVariable function to get variables for cloudflare

js/package.json, js/src/sdk/client/core/OpenAPI.ts, js/src/sdk/index.ts
…v variable
___
Enhancement
___
- Made the `BASE` URL configurable via the `COMPOSIO_BASE_URL` environment variable in `OpenAPIConfig`.
- Updated `Composio` class to use the `COMPOSIO_BASE_URL` environment variable for `baseUrl` initialization.
- Changed `getApiUrlBase` to a static method and updated relevant methods to use this new static method.
- Bumped the package version from `0.1.5` to `0.1.6-1` in `package.json`.
___
<tr>
<td>
<details>
<summary><strong>OpenAPI.ts</strong><dd><code>Make BASE URL configurable via environment variable</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
js/src/sdk/client/core/OpenAPI.ts
<li>Changed …
=> feat: add support for configuring BASE_URL using COMPOSIO_BASE_URL env

python/composio/tools/local/sqltool/actions/sql_query.py
Enhancement, Error handling
___
- Added a check to verify if the database file exists before attempting to connect.
- Wrapped database connection and query execution in a try-except block to handle potential SQLite errors.
- Ensured the database connection is closed properly in a finally block to avoid resource leaks.
___
<tr>
<td>
<details>
<summary><strong>sql_query.py</strong><dd><code>Enhance SQL query tool with error handling and file existence check</code></dd></summary>
<hr>
python/composio/tools/local/sqltool/actions/sql_query.py
<li>Added check for database file existence before attempting connection.<br> <li> Wrapped database operations in …
=> Update sql query tool

python/examples/rag_agent/.env.example
documentation
___
- Added `OPENAI_API_KEY` entry to the `.env.example` file in the RAG agent example directory.
- Included a placeholder comment to indicate where to place the OpenAI API key.
___
<tr>
<td>
<details>
<summary><strong>.env.example</strong><dd><code>Add `OPENAI_API_KEY` to `.env.example` for RAG agent example</code></dd></summary>
<hr>
python/examples/rag_agent/.env.example
<li>Added <code>OPENAI_API_KEY</code> entry to <code>.env.example</code> file.<br> <li> Provided a placeholder comment for the OpenAI API key.<br>
</details>
</td>
<td><a href="https://github.com/ComposioHQ/composio/pull/356/files#diff-dbb71cb09d5d8969cebf72ca888dc97b165 …
=> update: Add OPENAI_API_KEY key in .env.example of rag_agent example

js/examples/ai-playground-main/pnpm-lock.yaml, js/src/env/base.ts, js/src/env/docker/workspace.ts, js/src/env/e2b/workspace.ts, js/src/utils/shared.ts, js/wrangler.toml
Enhancement, Bug fix
___
- Refactored `DockerWorkspace` and `E2BWorkspace` classes to use `nodeExternalRequire` for dynamic module loading.
- Added type annotations and null checks in `DockerWorkspace` and `E2BWorkspace`.
- Simplified `Shell` class by removing `EventEmitter` inheritance.
- Added `nodeExternalRequire` utility function in `shared.ts`.
- Updated Wrangler configuration to enable Node.js compatibility.
___
<tr>
<td>
<details>
<summary><strong>workspace.ts</strong><dd><code>Refactor DockerWorkspace to use dynamic module loading and type </code><br><code>annotations</code></dd></summary>
<hr>
js/src/env/docker/workspace.ts
<li>Replaced direct …
=> fix: types for cloudflare framework

python/composio/tools/env/filemanager/file.py, python/swe/examples/crewai_agent/agent.py, python/swe/swekit/benchmark/utils.py, python/swe/swekit/scaffold/templates/crewai/agent.template, python/tests/test_tools/test_local/test_workspace.py
Enhancement, Tests
___
- Adjusted the error message in the `edit` function to return an empty string instead of "No lint errors found".
- Added a new `calculate_operation` action for basic arithmetic operations.
- Introduced a `get_langchain_llm` function to dynamically select the LLM based on environment variables in the CrewAI SWE Agent.
- Updated the agent initialization in the CrewAI SWE Agent to use the new `get_langchain_llm` function.
- Updated the `logs_dir` path in the `get_score` function call in the benchmark utility.
- Updated the `test_workspace` function with a new repository name and file path, and added additional logging for file scroll actions.
- Added the `calculate_operation` action to the agent template and appended it to the tools list.
___ …
=> Fix edit tool, add runtime action

python/composio/tools/env/filemanager/file.py, python/composio/tools/env/filemanager/manager.py, python/composio/tools/local/filetool/actions/chwdir.py, python/composio/tools/local/filetool/actions/edit.py, python/composio/tools/local/filetool/actions/git_patch.py, python/composio/tools/local/filetool/actions/open.py, python/composio/tools/local/filetool/actions/scroll.py, python/dockerfiles/Dockerfile.dev, python/dockerfiles/entrypoint.sh, python/swe/examples/crewai_agent/agent.py, python/swe/examples/crewai_agent/benchmark.py, python/swe/swekit/benchmark/run_evaluation.py, python/swe/swekit/benchmark/utils.py, python/tests/test_tools/test_local/test_workspace.py
Enhancement, Bug fix, Documentation
___
- Fixed indexing issue and improved methods in file manager.
- Enhanced directory change handling with additional checks.
- Clarified and validated file edit requests.
- Simplified empty patch response handling.
- Fixed total lines calculation in file open response.
- Added unique ID to scroll requests.
- Simplified agent tool initialization.
- Fixed syntax issue in benchmark function.
- Corrected log message typo.
- Updated log directory path.
- Enhanced workspace test with logging and assertions.
- Added installation of `composio-core` with all extras in dev mode.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>8 files</summary><table>
<tr>
<td> …
=> Fix SWE accuracy

python/plugins/phidata/README.md, python/plugins/phidata/composio_phidata/__init__.py, python/plugins/phidata/composio_phidata/toolset.py, python/plugins/phidata/phidata_demo.py, python/plugins/phidata/setup.py
No changes other than the phidata plugin
=> Phidata plugin[ONLY]

python/composio/tools/base/local.py, python/composio/tools/env/base.py, python/examples/sql_agent/log.txt, python/tests/test_tools/test_local/test_filetool.py
=> Add files tools test

.github/workflows/examples.yml
Send slack notif if examples failed
=> Send slack notif if examples failed

js/src/sdk/index.ts, js/src/sdk/utils/other.ts, js/src/sdk/utils/projectUtils.ts
```
🚀 Upgrade available! Your composio-core version (0.1.12) is behind. Latest version: 0.1.16.
```
- Message which we're showing.
- Tested locally with generated build.
- In case of error, do nothing.
=> feat: js show warning to update to latest version

js/src/sdk/models/actions.ts, js/src/sdk/models/triggers.spec.ts, js/src/sdk/models/triggers.ts, js/src/sdk/utils/pusher.ts
- Creates an issue and listens for a trigger
=> feat: add trigger e2e test #ENG-1097

js/package.json, js/src/cli/add.ts, js/src/sdk/models/integrations.ts
- add support ```composio add github --force --skip-default-connector``
- fix bug with creating connection
=> feat: add support for skip default connector #ENG-1386

README-CN.md, README-JP.md, README.md
This pull-request updates the links to `banner.gif`. There are two commits, which are related to this:
- 255e58b1817c6b7d3649123281af099e3445e876
- 24cdfdb3f2ae30f0ce3ea5f9b31a152f427a2a44
=> docs: update links to `banner.gif`

python/composio/utils/sentry.py
Ensures `KeyboardInterrupt` errors don't end up on sentry.
=> chore: ignore keyboard interrupts for sentry alerts

python/setup.py, python/tox.ini
Pydantic 2.10 right now is causing mypy failures. Better to wait until they fix that problem before we bump to 2.10
=> Pin `pydantic<2.10`

js/src/sdk/index.ts
Improve user experience by providing clearer instructions on passing the API key in the `Composio` class.
- **Enhancement**:
- Enhanced error message in the `Composio` class to guide users on passing the API key via the constructor or as an environment variable.
Enhances the user experience by offering more precise guidance for resolving potential API key configuration issues, resulting in improved clarity and user experience. 
</details>
=> fix: Updated error message

python/plugins/phidata/composio_phidata/toolset.py, python/plugins/phidata/phidata_demo.py
Refactor the Phidata plugin for enhanced modularity and improved functionality.
- **Refactor**
- Replaced the `Function` class with the `Toolkit` class in `toolset.py`.
- Improved docstrings for better code documentation.
- Clarified import statements for easier code navigation.
- Removed redundant spaces to enhance code readability.
- **Enhancement**
- Updated `phidata_demo.py` to align with the new toolkit structure.
- Transitioned from `get_actions` to `get_tools` for better functionality.
- Eliminated unnecessary print statements to clean up the code.
The changes have streamlined operations and improved code clarity, leading to a more efficient and user-friendly experience within the Phidata plugin.  …
=> Update phidata plugin for use toolkit

docs/api-reference/client/delete-project.mdx, docs/mint.json
**Purpose**:
- Updated API documentation by removing deprecated content.
**Changes**:
- **Documentation**: Eliminated the 'delete project' API endpoint from markdown and JSON configuration files.
**Impact**:
- Enhanced documentation clarity and ease of maintenance. 
</details>
=> fix: remove delete project api doc

python/plugins/langchain/composio_langchain/toolset.py
Validation errors handled in composio langchain
=> fix: bug in composio langchain

.gitignore, fern/authentication/auth-lifecycle.mdx, fern/authentication/custom-auth.mdx, fern/authentication/introduction.mdx, fern/docs.yml, fern/generators/tool_doc_generator/main.py, fern/getting-started/welcome.mdx, fern/tools/introduction.mdx
- Added a new document for "Auth Lifecycle" detailing the integration and connection process.
- Updated "Custom Auth" to "Custom Authentication Guide" with improved clarity and structure.
- Introduced "Introduction" page for tools in the documentation.
- Adjusted navigation paths in the documentation for better organization.
- Updated .gitignore to include specific files for tools and documentation.
=> feat: update authentication documentation 

js/src/sdk/base.toolset.ts
- added condition to check and get `connectedAccountId` from connectedAccountIds field in` executeAction()` method of `base.toolset`
=> fix: add condition to get connectedAccId from connectedAccountIds field

python/composio/tools/base/abs.py
This pull request adds a new attribute to the `Action` class in `python/composio/tools/base/abs.py`. The change introduces the `scopes` attribute to define optional scopes required for the action.
=> feat: adding scopes parameter to action model

ts/examples/anthropic/src/mcp.ts, ts/packages/providers/anthropic/src/index.ts
Add MCP support for Anthropic and added relevant example
=> feat: add support for anthropic

fern/mcp/introduction.mdx
Updated MCP docs; Support for MCP transport is added.
=> fix: updated mcp docs, added new transport method

fern/pages/src/mcp/partner-api.mdx, fern/pages/src/mcp/providers.mdx
Added auth config id in the docs; mcp provider
=> feat: updated mcp docs

fern/pages/src/mcp/introduction.mdx
=> feat: updated mcp v3 docs

.changeset/pre.json, .changeset/thick-keys-work.md, pnpm-lock.yaml, ts/packages/core/CHANGELOG.md, ts/packages/core/package.json, ts/packages/json-schema-to-zod/CHANGELOG.md, ts/packages/json-schema-to-zod/package.json, ts/packages/providers/anthropic/CHANGELOG.md, ts/packages/providers/anthropic/package.json, ts/packages/providers/cloudflare/CHANGELOG.md, ts/packages/providers/cloudflare/package.json, ts/packages/providers/google/CHANGELOG.md, ts/packages/providers/google/package.json, ts/packages/providers/langchain/CHANGELOG.md, ts/packages/providers/langchain/package.json, ts/packages/providers/mastra/CHANGELOG.md, ts/packages/providers/mastra/package.json, ts/packages/providers/openai-agents/CHANGELOG.md, ts/packages/providers/openai-agents/package.json, ts/packages/providers/openai/CHANGELOG.md, ts/packages/providers/openai/package.json, ts/packages/providers/vercel/CHANGELOG.md, ts/packages/providers/vercel/package.json
Bunch of fixes
- Connected account initiation fix where the data wasn't being passes
- Exported missing types
- Connected accounts initiation auth scheme type fixes
=> Release ts SDK @ next6

.changeset/pre.json, .changeset/slimy-showers-burn.md, ts/packages/core/CHANGELOG.md, ts/packages/core/package.json, ts/packages/providers/anthropic/CHANGELOG.md, ts/packages/providers/anthropic/package.json, ts/packages/providers/cloudflare/CHANGELOG.md, ts/packages/providers/cloudflare/package.json, ts/packages/providers/google/CHANGELOG.md, ts/packages/providers/google/package.json, ts/packages/providers/langchain/CHANGELOG.md, ts/packages/providers/langchain/package.json, ts/packages/providers/mastra/CHANGELOG.md, ts/packages/providers/mastra/package.json, ts/packages/providers/openai-agents/CHANGELOG.md, ts/packages/providers/openai-agents/package.json, ts/packages/providers/openai/CHANGELOG.md, ts/packages/providers/openai/package.json, ts/packages/providers/vercel/CHANGELOG.md, ts/packages/providers/vercel/package.json
Bumps package versions to latest release candidates
=> Bump package versions

.changeset/soft-corners-tell.md, pnpm-lock.yaml, ts/packages/json-schema-to-zod/src/parsers/parse-array.ts, ts/packages/json-schema-to-zod/src/parsers/parse-object.ts, ts/packages/json-schema-to-zod/test/json-to-zod.test.ts
- Fixes issues related to JSON schema to zod parsing when items have default as null
- Fixes issues with array parsing
=> Fix: JSON Schema to Zod Parsing errors in default/arrays

pnpm-lock.yaml, ts/examples/json-schema-to-zod/package.json, ts/packages/core/CHANGELOG.md, ts/packages/core/package.json, ts/packages/json-schema-to-zod/CHANGELOG.md, ts/packages/json-schema-to-zod/package.json, ts/packages/json-schema-to-zod/src/parsers/parse-array.ts, ts/packages/json-schema-to-zod/src/parsers/parse-number.ts, ts/packages/json-schema-to-zod/src/parsers/parse-schema.ts, ts/packages/json-schema-to-zod/src/parsers/parse-string.ts, ts/packages/json-schema-to-zod/src/utils/extend-schema.ts, ts/packages/json-schema-to-zod/test/json-to-zod.test.ts, ts/packages/providers/anthropic/CHANGELOG.md, ts/packages/providers/anthropic/package.json, ts/packages/providers/cloudflare/CHANGELOG.md, ts/packages/providers/cloudflare/package.json, ts/packages/providers/google/CHANGELOG.md, ts/packages/providers/google/package.json, ts/packages/providers/langchain/CHANGELOG.md, ts/packages/providers/langchain/package.json, ts/packages/providers/mastra/CHANGELOG.md, ts/packages/providers/mastra/package.json, ts/packages/providers/openai-agents/CHANGELOG.md, ts/packages/providers/openai-agents/package.json, ts/packages/providers/openai/CHANGELOG.md, ts/packages/providers/openai/package.json, ts/packages/providers/vercel/CHANGELOG.md, ts/packages/providers/vercel/package.json
Fixes isssues with zod schema parsing
- Fixes min/max properties getting dropped
- Fixes examples getting dropped, get's added along with descriptions
=> Fix zodschema parsing

.changeset/upset-hands-divide.md, pnpm-lock.yaml, ts/packages/core/package.json
Bumps composio client version to 0.1.0-alpha.31
=> Chore: Bump Composio/Client packages

.changeset/proud-snails-search.md, pnpm-lock.yaml, ts/examples/vercel/src/index.ts, ts/examples/vercel/src/types.ts, ts/packages/core/src/types/authConfigs.types.ts, ts/packages/core/src/utils/jsonSchema.ts, ts/packages/providers/vercel/src/index.ts
- Adds strict mode in vercel ai sdk
- Fixes auth config update methods
=> Adds strict mode in Vercel AI SDK + Minor bug fixes

python/CHANGELOG.md, python/pyproject.toml
Fixes around triggers have been on next branch but not released. this PR symbolizes releasing them.
=> chore: release 0.8.10

python/composio/core/models/triggers.py
=> Get connected account for user (user_id)

python/composio/__init__.py, python/composio/core/models/tools.py, python/composio/sdk.py, python/composio/types.py, python/composio/utils/toolkit_version.py
Added changes needed for versioning support in python sdk. Untested and needs some testing.
=> feat: add versioning to py sdk

README.md, fern/generators/tool_doc_generator/main.py, fern/pages/src/examples/utility_agents/supabase_sql_agent.mdx, fern/pages/src/get-started/quickstart.mdx
This might be a very temporary fix. But for some reason they need this to approve our app. So keeping our best judgement aside we are doing this.
=> Docs: Monday needs to use 'monday' for app approval

fern/docs.yml, uv.lock
docs build is locally failing regenerated using pnpm tools:generate
=> Docs: Fix tool kit generation error for local dev
